import type { StatusFilter } from './types';

export const DEFAULT_WATERMARK_TEXT = 'generated by xcity ai studio';

export const MAX_WATERMARK_TEXT_LENGTH = 100;

export const MAX_CONCURRENT_WATERMARKS = 2;

export const STATUS_FILTERS: Array<{ id: StatusFilter; label: string }> = [
    { id: 'all', label: 'All' },
    { id: 'completed', label: 'Completed' },
    { id: 'processing', label: 'Processing' },
    { id: 'archiving', label: 'Archiving' },
    { id: 'failed', label: 'Failed' }
];
