import type { SocialShareTarget } from './types';

export const MAX_REFERENCE_VIDEOS = 2;

export const SHARE_PROMPT_LIMIT = 4000;

export const BRANDING_WATERMARK_TEXT = 'generated by xcity ai studio';

export const MAX_WATERMARK_TEXT_LENGTH = 100;

export const SOCIAL_SHARE_TARGETS: SocialShareTarget[] = [
    {
        id: 'tiktok',
        label: 'TikTok',
        url: () => 'https://www.tiktok.com/upload',
        copyFirst: true
    },
    {
        id: 'instagram',
        label: 'Instagram',
        url: () => 'https://www.instagram.com/',
        copyFirst: true
    },
    {
        id: 'youtube',
        label: 'YouTube',
        url: () => 'https://www.youtube.com/upload',
        copyFirst: true
    },
    {
        id: 'facebook',
        label: 'Facebook',
        url: (shareUrl) => `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`
    },
    {
        id: 'twitter',
        label: 'Twitter',
        url: (shareUrl) =>
            `https://twitter.com/intent/tweet?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(
                'Created with Xcity Studio'
            )}`
    }
];

export const FINALIZE_UNSUPPORTED_MODEL_MESSAGE = 'Finalize is only available for Seedance 2.5 drafts.';
